version: '3.7'
services:
  kurento:
    image: kurento/kurento-media-server:7.0.0
    network_mode: host
    restart: always
    environment:
      - KMS_STUN_IP= stun.l.google.com
      - KMS_STUN_PORT= 19302
      - KMS_EXTERNAL_IPV4= 3.39.179.45

  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"

  spring:
    build: .
    ports:
      - "8081:8081"