version: '3.7'
services:
  kurento:
    image: cit_kurento:latest
    container_name: kurento
    restart: always
    network_mode: host

  nginx:
    image: cit_nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"

  spring:
    depends_on: [ kurento,nginx ]
    image: cit_spring:latest
    container_name: spring
    ports:
      - "8081:8081"