name: Deploy Project
on:
  push:
    branches: [ "main","develop" ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.KEY }}
      - name: Run Script
        run: ls -al;
