name: Deploy Project
on:
  push:
    branches: [ "main","develop" ]

jobs:
  build-and-push:
    name: upload
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push - kurento
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_kurento
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cit_kurento:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push - nginx
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_nginx
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cit_nginx:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push - spring
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_spring
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cit_spring:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: deploy
    needs: build-and-push
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            docker-compose down
            docker rm -f $(docker ps -aq)
            docker rmi $(docker images -q)
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cit_kurento:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cit_nginx:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/cit_spring:latest
            docker-compose up -d
            




